### ISSUE TITLE
Facebook phishlets

### ISSUE THREAD

**Issue by maskedTigger** [d0n601/Evilginx3-Phishlet-Playground#1]
Can you make a facebook phishlets please

**Comment by MTalha1276** [comment]
yes please

**Comment by GoogleDork** [comment]
also a gmail!

**Comment by Dazmed707** [comment]
I have available facebook and google, and others phishlet availables.
telegram: @stfj99

**Comment by d0n601** [comment]
![bushes-7d6b](https://github.com/d0n601/Evilginx3-Phishlet-Playground/assets/8961705/7decda36-7889-49fb-9de9-0d9700d3d625)
